name: intrinsic_value
description: This Dart project offers tools for financial analysis.
version: 1.0.0
repository: https://github.com/Appjetive/intrinsic_value

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  args: ^2.4.2
  fpdart: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.25.8
