name: intrinsic_value
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  args: ^2.4.2
  fpdart: ^1.1.0
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.8
  lints: ^2.0.0
  riverpod_generator: ^2.4.0
  test: ^1.21.0
