name: Lint and Tests Validation

on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

env:
  dart_version: "3.0.1"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get
      - name: Build runner
        run: dart run build_runner build
      - name: Check code format
        run: dart format -o none --set-exit-if-changed .
      - name: Check Linting rules
        run: flutter analyze --no-pub
      - name: Run tests
        run: dart test
